VideoGames.destroy_all
Developers.destroy_all
Customers.destroy_all


kenzo = Developers.create(:name=> 'Kenzo Tsujimoto')
yoshiki = Developers.create(:name=> 'Yoshiki Okamoto')
emily = Developers.create(:name=> 'Emily Braman')
fusajiro = Developers.create(:name=> 'Fusajiro Yamauchi')
mario = Developers.create(:name=> 'Mario Bros')
luigi = Developers.create(:name=> 'Luigi Bros')
todd = Developers.create(:name=> 'Todd Howard')
ashley = Developers.create(:name=> 'Ashley Cheng')
alex = Developers.create(:name=> 'Alex Seropian')
seth = Developers.create(:name=> 'Seth Starr')
pete = Developers.create(:name=> 'Pete Parsons')
jason = Developers.create(:name=> 'Jason Jones')
marie = Developers.create(:name=> 'Marie Brown')
josue = Developers.create(:name=> 'Josue Viramontes')

kh3 = VideoGames.create(:name=> 'Kingdom Hearts 3', :publishyear=> 2019, :genre=> 'Adventure', :platform=> 'Playstation 4', :ersb=> 'E')
uncharted = VideoGames.create(:name=> 'Uncharted 2', :publishyear=> 2008, :genre=> 'Action', :platform=> 'Playstation 3', :ersb=> 'T')
crash = VideoGames.create(:name=> 'Crash Bandicoot', :publishyear=> 1995, :genre=> 'Adventure', :platform=> 'Playstation 1', :ersb=> 'E')
need = VideoGames.create(:name=> 'Need for Speed', :publishyear=> 2007, :genre=> 'Racing', :platform=> 'Xbox 360', :ersb=> 'E')
madden = VideoGames.create(:name=> 'Madden', :publishyear=> 2012, :genre=> 'Sports', :platform=> 'Xbox One', :ersb=> 'E')
re = VideoGames.create(:name=> 'Resident Evil', :publishyear=> 2012, :genre=> 'Action', :platform=> 'Playstation 3', :ersb=> 'M')
gt = VideoGames.create(:name=> 'Gran Turismo', :publishyear=> 2007, :genre=> 'Racing', :platform=> 'Playstation 3', :ersb=> 'T')
zelda = VideoGames.create(:name=> 'The Legend of Zelda', :publishyear=> 1999, :genre=> 'Adventure', :platform=> 'Nintendo 64', :ersb=> 'E')
mk = VideoGames.create(:name=> 'Mortal Kombat', :publishyear=> 1995, :genre=> 'Action', :platform=> 'Playstation 1', :ersb=> 'M')
rd = VideoGames.create(:name=> 'Red Dead Redemption', :publishyear=> 2012, :genre=> 'Adventure', :platform=> 'PC', :ersb=> 'M')
fifa = VideoGames.create(:name=> 'Fifa', :publishyear=> 2012, :genre=> 'Sports', :platform=> 'Xbox One', :ersb=> 'T')
ban = VideoGames.create(:name=> 'Batman Arkham Night', :publishyear=> 2011, :genre=> 'Adventure', :platform=> 'PC', :ersb=> 'M')
splinter = VideoGames.create(:name=> 'Splinter Cell', :publishyear=> 2010, :genre=> 'Action', :platform=> 'Playstation 2', :ersb=> 'M')
mine = VideoGames.create(:name=> 'Minecraft', :publishyear=> 2010, :genre=> 'Adventure', :platform=> 'PC', :ersb=> 'E')

george= Customers.create(:name=> 'George Smith', :age=> 13, :location=> 'USA')
anna= Customers.create(:name=> 'Anna Kendrick', :age=> 24, :location=> 'USA')
larz= Customers.create(:name=> 'Larz Barro', :age=> 24, :location=> 'CANADA')
hilary= Customers.create(:name=> 'Hilary Smith', :age=> 36, :location=> 'BRAZIL')
mary= Customers.create(:name=> 'Mary Mallard', :age=> 20, :location=> 'U.K.')
richard= Customers.create(:name=> 'Richard Hicks', :age=> 31, :location=> 'U.K')
sam= Customers.create(:name=> 'Sam Jerry', :age=> 99, :location=> 'JAPAN')
larry= Customers.create(:name=> 'Larry King', :age=> 10, :location=> 'JAPAN')
smithers= Customers.create(:name=> 'Smithers Loon', :age=> 8, :location=> 'JAPAN')
star= Customers.create(:name=> 'Star Jones', :age=> 10, :location=> 'CHINA')
harry= Customers.create(:name=> 'Harry Smith', :age=> 24, :location=> 'USA')
miller= Customers.create(:name=> 'Miller Smith', :age=> 36, :location=> 'USA')
lara= Customers.create(:name=> 'Lara Mallard', :age=> 15, :location=> 'U.K.')
will= Customers.create(:name=> 'Will Jerry', :age=> 6, :location=> 'BRAZIL')